spring.application.name=content
spring.profiles.active=prod

spring.data.mongodb.uri=mongodb://localhost:27017/contentdb

openai.api.url=https://api.openai.com

spring.datasource.url=jdbc:postgresql://localhost:5432/contentdb
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.security.oauth2.client.registration.google.client-id=916782596266-tdjnnnl8csh15oeghn6h9fid4u4qsf98.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

