package com.app.categorise.data.repository;

import com.app.categorise.data.entity.TranscriptEntity;

import java.time.Instant;
import java.util.List;

/**
 * Defines custom repository methods for the Transcript entity that are not automatically generated by Spring Data.
 */
public interface CustomTranscriptRepository {
    List<TranscriptEntity> filter(List<String> categories, String account, Instant from, Instant to);
}
