package com.app.categorise.data.repository;

import com.app.categorise.data.entity.TranscriptEntity;

import java.time.Instant;
import java.util.List;

/**
 * Defines custom repository methods for the Transcript entity that are not automatically generated by Spring Data.
 */
public interface CustomTranscriptRepository {
    List<TranscriptEntity> filter(List<String> categories, String account, Instant from, Instant to);
    /**
     * Performs a bulk update to change the alias for all transcripts matching a specific user and grouping key.
     *
     * @param userId The ID of the user whose transcripts will be updated.
     * @param groupingKey The grouping key (e.g., "Recipe" or "tech") to identify the target transcripts.
     * @param newAlias The new alias to set on the matching transcripts.
     */
    void updateAliasForUserAndGroupingKey(String userId, String groupingKey, String newAlias);
}
